# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/s15_group4/Desktop/RPB_ColorConnections

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/s15_group4/Desktop/RPB_ColorConnections

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/s15_group4/Desktop/RPB_ColorConnections/CMakeFiles /home/s15_group4/Desktop/RPB_ColorConnections/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/s15_group4/Desktop/RPB_ColorConnections/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named RPB_4

# Build rule for target.
RPB_4: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RPB_4
.PHONY : RPB_4

# fast build rule for target.
RPB_4/fast:
	$(MAKE) -f CMakeFiles/RPB_4.dir/build.make CMakeFiles/RPB_4.dir/build
.PHONY : RPB_4/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/RPB_4.dir/build.make CMakeFiles/RPB_4.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/RPB_4.dir/build.make CMakeFiles/RPB_4.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/RPB_4.dir/build.make CMakeFiles/RPB_4.dir/main.cpp.s
.PHONY : main.cpp.s

src/BridgeInterface.o: src/BridgeInterface.cpp.o
.PHONY : src/BridgeInterface.o

# target to build an object file
src/BridgeInterface.cpp.o:
	$(MAKE) -f CMakeFiles/RPB_4.dir/build.make CMakeFiles/RPB_4.dir/src/BridgeInterface.cpp.o
.PHONY : src/BridgeInterface.cpp.o

src/BridgeInterface.i: src/BridgeInterface.cpp.i
.PHONY : src/BridgeInterface.i

# target to preprocess a source file
src/BridgeInterface.cpp.i:
	$(MAKE) -f CMakeFiles/RPB_4.dir/build.make CMakeFiles/RPB_4.dir/src/BridgeInterface.cpp.i
.PHONY : src/BridgeInterface.cpp.i

src/BridgeInterface.s: src/BridgeInterface.cpp.s
.PHONY : src/BridgeInterface.s

# target to generate assembly for a file
src/BridgeInterface.cpp.s:
	$(MAKE) -f CMakeFiles/RPB_4.dir/build.make CMakeFiles/RPB_4.dir/src/BridgeInterface.cpp.s
.PHONY : src/BridgeInterface.cpp.s

src/BridgeModel.o: src/BridgeModel.cpp.o
.PHONY : src/BridgeModel.o

# target to build an object file
src/BridgeModel.cpp.o:
	$(MAKE) -f CMakeFiles/RPB_4.dir/build.make CMakeFiles/RPB_4.dir/src/BridgeModel.cpp.o
.PHONY : src/BridgeModel.cpp.o

src/BridgeModel.i: src/BridgeModel.cpp.i
.PHONY : src/BridgeModel.i

# target to preprocess a source file
src/BridgeModel.cpp.i:
	$(MAKE) -f CMakeFiles/RPB_4.dir/build.make CMakeFiles/RPB_4.dir/src/BridgeModel.cpp.i
.PHONY : src/BridgeModel.cpp.i

src/BridgeModel.s: src/BridgeModel.cpp.s
.PHONY : src/BridgeModel.s

# target to generate assembly for a file
src/BridgeModel.cpp.s:
	$(MAKE) -f CMakeFiles/RPB_4.dir/build.make CMakeFiles/RPB_4.dir/src/BridgeModel.cpp.s
.PHONY : src/BridgeModel.cpp.s

src/Color.o: src/Color.cpp.o
.PHONY : src/Color.o

# target to build an object file
src/Color.cpp.o:
	$(MAKE) -f CMakeFiles/RPB_4.dir/build.make CMakeFiles/RPB_4.dir/src/Color.cpp.o
.PHONY : src/Color.cpp.o

src/Color.i: src/Color.cpp.i
.PHONY : src/Color.i

# target to preprocess a source file
src/Color.cpp.i:
	$(MAKE) -f CMakeFiles/RPB_4.dir/build.make CMakeFiles/RPB_4.dir/src/Color.cpp.i
.PHONY : src/Color.cpp.i

src/Color.s: src/Color.cpp.s
.PHONY : src/Color.s

# target to generate assembly for a file
src/Color.cpp.s:
	$(MAKE) -f CMakeFiles/RPB_4.dir/build.make CMakeFiles/RPB_4.dir/src/Color.cpp.s
.PHONY : src/Color.cpp.s

src/ColorPanel.o: src/ColorPanel.cpp.o
.PHONY : src/ColorPanel.o

# target to build an object file
src/ColorPanel.cpp.o:
	$(MAKE) -f CMakeFiles/RPB_4.dir/build.make CMakeFiles/RPB_4.dir/src/ColorPanel.cpp.o
.PHONY : src/ColorPanel.cpp.o

src/ColorPanel.i: src/ColorPanel.cpp.i
.PHONY : src/ColorPanel.i

# target to preprocess a source file
src/ColorPanel.cpp.i:
	$(MAKE) -f CMakeFiles/RPB_4.dir/build.make CMakeFiles/RPB_4.dir/src/ColorPanel.cpp.i
.PHONY : src/ColorPanel.cpp.i

src/ColorPanel.s: src/ColorPanel.cpp.s
.PHONY : src/ColorPanel.s

# target to generate assembly for a file
src/ColorPanel.cpp.s:
	$(MAKE) -f CMakeFiles/RPB_4.dir/build.make CMakeFiles/RPB_4.dir/src/ColorPanel.cpp.s
.PHONY : src/ColorPanel.cpp.s

src/MainLoop.o: src/MainLoop.cpp.o
.PHONY : src/MainLoop.o

# target to build an object file
src/MainLoop.cpp.o:
	$(MAKE) -f CMakeFiles/RPB_4.dir/build.make CMakeFiles/RPB_4.dir/src/MainLoop.cpp.o
.PHONY : src/MainLoop.cpp.o

src/MainLoop.i: src/MainLoop.cpp.i
.PHONY : src/MainLoop.i

# target to preprocess a source file
src/MainLoop.cpp.i:
	$(MAKE) -f CMakeFiles/RPB_4.dir/build.make CMakeFiles/RPB_4.dir/src/MainLoop.cpp.i
.PHONY : src/MainLoop.cpp.i

src/MainLoop.s: src/MainLoop.cpp.s
.PHONY : src/MainLoop.s

# target to generate assembly for a file
src/MainLoop.cpp.s:
	$(MAKE) -f CMakeFiles/RPB_4.dir/build.make CMakeFiles/RPB_4.dir/src/MainLoop.cpp.s
.PHONY : src/MainLoop.cpp.s

src/TravelingColor.o: src/TravelingColor.cpp.o
.PHONY : src/TravelingColor.o

# target to build an object file
src/TravelingColor.cpp.o:
	$(MAKE) -f CMakeFiles/RPB_4.dir/build.make CMakeFiles/RPB_4.dir/src/TravelingColor.cpp.o
.PHONY : src/TravelingColor.cpp.o

src/TravelingColor.i: src/TravelingColor.cpp.i
.PHONY : src/TravelingColor.i

# target to preprocess a source file
src/TravelingColor.cpp.i:
	$(MAKE) -f CMakeFiles/RPB_4.dir/build.make CMakeFiles/RPB_4.dir/src/TravelingColor.cpp.i
.PHONY : src/TravelingColor.cpp.i

src/TravelingColor.s: src/TravelingColor.cpp.s
.PHONY : src/TravelingColor.s

# target to generate assembly for a file
src/TravelingColor.cpp.s:
	$(MAKE) -f CMakeFiles/RPB_4.dir/build.make CMakeFiles/RPB_4.dir/src/TravelingColor.cpp.s
.PHONY : src/TravelingColor.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... RPB_4"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/BridgeInterface.o"
	@echo "... src/BridgeInterface.i"
	@echo "... src/BridgeInterface.s"
	@echo "... src/BridgeModel.o"
	@echo "... src/BridgeModel.i"
	@echo "... src/BridgeModel.s"
	@echo "... src/Color.o"
	@echo "... src/Color.i"
	@echo "... src/Color.s"
	@echo "... src/ColorPanel.o"
	@echo "... src/ColorPanel.i"
	@echo "... src/ColorPanel.s"
	@echo "... src/MainLoop.o"
	@echo "... src/MainLoop.i"
	@echo "... src/MainLoop.s"
	@echo "... src/TravelingColor.o"
	@echo "... src/TravelingColor.i"
	@echo "... src/TravelingColor.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

